# Generated by Django 4.2.5 on 2023-09-20 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='costcenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costType', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Cost Center',
                'verbose_name_plural': 'Cost Center',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Division',
            },
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobType', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Job Type',
                'verbose_name_plural': 'Job Type',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(blank=None, max_length=200)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Project',
            },
        ),
        migrations.CreateModel(
            name='SalaryGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_grade', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Salary Type',
                'verbose_name_plural': 'Salary Type',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medal', models.CharField(blank=True, choices=[('Active', 'Active'), ('Transferred', 'Transferred'), ('Contract', 'Contract'), ('Ended', 'Ended'), ('Resigned', 'Resigned'), ('Terminated', 'Terminated')], max_length=100)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='VisaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visaType', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Visa Type',
                'verbose_name_plural': 'Visa Type',
            },
        ),
        migrations.CreateModel(
            name='EmployDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('comments', models.CharField(blank=None, max_length=200)),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employdata.costcenter', verbose_name='Cost Center')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employdata.division', verbose_name='Division')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employdata.jobtype', verbose_name='Job Type')),
                ('project', models.ForeignKey(blank=None, on_delete=django.db.models.deletion.CASCADE, to='employdata.project', verbose_name='Project')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employdata.salarygrade', verbose_name='Salary Grade')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employdata.status', verbose_name='Sataus')),
                ('visa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employdata.visatype', verbose_name='Visa')),
            ],
            options={
                'verbose_name': 'Employ Profile',
            },
        ),
    ]
