# Generated by Django 4.2.5 on 2023-09-20 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employdetails',
            name='comments',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='employdetails',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='employdata.project', verbose_name='Project'),
        ),
    ]
