# Generated by Django 4.2.5 on 2023-09-20 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employdata', '0002_alter_employdetails_comments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costcenter',
            options={'verbose_name': 'Cost Center', 'verbose_name_plural': 'Cost Centers'},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'verbose_name': 'Division', 'verbose_name_plural': 'Divisions'},
        ),
        migrations.AlterModelOptions(
            name='jobtype',
            options={'verbose_name': 'Job Type', 'verbose_name_plural': 'Job Types'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='salarygrade',
            options={'verbose_name': 'Salary Grade', 'verbose_name_plural': 'Salary Grades'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
        migrations.AlterModelOptions(
            name='visatype',
            options={'verbose_name': 'Visa Type', 'verbose_name_plural': 'Visa Types'},
        ),
        migrations.RenameField(
            model_name='costcenter',
            old_name='costType',
            new_name='cost_type',
        ),
        migrations.RenameField(
            model_name='jobtype',
            old_name='jobType',
            new_name='job_type',
        ),
        migrations.RenameField(
            model_name='visatype',
            old_name='visaType',
            new_name='visa_type',
        ),
        migrations.RemoveField(
            model_name='status',
            name='medal',
        ),
        migrations.AddField(
            model_name='status',
            name='status_type',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Transferred', 'Transferred'), ('Contract Ended', 'Contract Ended'), ('Resigned', 'Resigned'), ('Terminated', 'Terminated')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employdetails',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employdata.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
