# Generated by Django 4.2.5 on 2023-09-20 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employdata', '0003_alter_costcenter_options_alter_division_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employdetails',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employdata.project', verbose_name='Project'),
        ),
    ]
