# Generated by Django 4.2.5 on 2023-09-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employdata', '0004_alter_employdetails_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
        migrations.RemoveField(
            model_name='status',
            name='status_type',
        ),
        migrations.AddField(
            model_name='status',
            name='medal',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Transferred', 'Transferred'), ('Contract', 'Contract'), ('Ended', 'Ended'), ('Resigned', 'Resigned'), ('Terminated', 'Terminated')], max_length=100),
        ),
    ]
